### ISSUE TITLE
Want to refactor `runstrax.py` and `strax-wrapper.sh`

### ISSUE THREAD

**Issue by FaroutYLq** [XENONnT/outsource#142]
The plan is to use more modern strax context definition to avoid handmade backend. We suspect the length mismatch issue #150 comes from here.

**Comment by FaroutYLq** [comment]
if the hypothesis in #150 is correct, the chunk merging bug is nothing to do with the storage magic here. If so we don't have to refactor here.

**Comment by dachengx** [comment]
MISSION ACCOMPLISHED

**Comment by dachengx** [comment]
By https://github.com/XENONnT/outsource/blob/7a2e726be97ba1f97010d44f0c2d685a49ef84fd/outsource/workflow/combine.py#L40 and https://github.com/AxFoundation/strax/pull/863
