### ISSUE TITLE
Need  a refactor -- memory issues

### ISSUE THREAD

**Issue by ershockley** [XENONnT/outsource#19]
It should've been clear at the beginning, but creating a large list of DBConfig objects does not scale well to large reprocessings. We should refactor things a bit to have outsource take a list of run numbers, not a list of these relatively heavy config objects. Also many attributes of the DBConfig class are more natural for the Outsource class (like context, force_rerun, etc).

**Comment by FaroutYLq** [comment]
Not sure if this issue still exists. Currently it is OK to handle ~100 runs in each workflow. Closing now.
