### ISSUE TITLE
per_chunk_data_types missing for muon veto

### ISSUE THREAD

**Issue by shenyangshi** [XENONnT/outsource#218]
https://github.com/XENONnT/outsource/blob/aac30a1f0936e630bbde3926e0fbf065dff40c13/outsource/config.py#L163-L170

**To reproduce this issue:**
`python3 $HOME/outsource/outsource/scripts/submit.py --context xenonnt_offline --xedocs_version global_v16 --image development --run 50775 --ignore_processed --local_transfer --debug`

**Error:**
```
Traceback (most recent call last):
  File "/home/shenyangshi/outsource/outsource/scripts/submit.py", line 139, in <module>
    main()
  File "/home/shenyangshi/outsource/outsource/scripts/submit.py", line 135, in main
    submitter.submit()
  File "/home/shenyangshi/outsource/outsource/submitter.py", line 870, in submit
    workflow = self._generate_workflow()
  File "/home/shenyangshi/outsource/outsource/submitter.py", line 768, in _generate_workflow
    dbcfg = RunConfig(self.context, run_id, ignore_processed=self.ignore_processed)
  File "/home/shenyangshi/outsource/outsource/config.py", line 85, in __init__
    self.data_types = self.deduce_data_types()
  File "/home/shenyangshi/outsource/outsource/config.py", line 169, in deduce_data_types
    raise ValueError("Why is there no per-chunk data_type deduced?")
ValueError: Why is there no per-chunk data_type deduced?
```

**Reason:**
No possible [muon veto data type](https://github.com/XENONnT/outsource/blob/aac30a1f0936e630bbde3926e0fbf065dff40c13/outsource/meta.py#L38) is In [per chunk data type](https://github.com/XENONnT/outsource/blob/aac30a1f0936e630bbde3926e0fbf065dff40c13/outsource/meta.py#L2-L7).

What's the preference to fix this? We can either bypass the check for muon veto, or add a per chunk data type for muon veto? @dachengx

**Comment by dachengx** [comment]
I prefer the latter.

**Comment by dachengx** [comment]
I can not reproduce the error.

**Comment by dachengx** [comment]
Did you change the code by your self?

**Comment by shenyangshi** [comment]
I added a few pdb function for debug, so the Error line number is not the same. Please see the link for the exact location.

**Comment by dachengx** [comment]
I can not see a bug at all. When report bug, please include the XENON_CONFIG as well. For REPRODUCIBILITY.

**Comment by shenyangshi** [comment]
Sure, let me send in slack. this is a public repo.

**Comment by FaroutYLq** [comment]
Just want to comment here: raw_records_mv are very small, and it doesn't worth the effort and resources to make them per-chunk job in my opinion.

**Comment by dachengx** [comment]
> Sure, let me send in slack. this is a public repo.

You can just paste the "Outsource" section here.

**Comment by shenyangshi** [comment]
```
[Outsource]
work_dir = /scratch/$USER/workflows
user_install_package = strax, straxen, cutax, rucio, utilix, admix, outsource
check_user_install_package = strax, straxen, cutax, rucio, utilix, admix, outsource
# sites to exclude (GLIDEIN_Site), comma seprated list
exclude_sites = SU-ITS, NotreDame, UConn-HPC, Purdue Geddes, Chameleon, WSU-GRID, SIUE-CC-production, Lancium
# data type to process
include_data_types = peaklets, hitlets_nv, events_nv, events_mv, event_info_double, afterpulses, led_calibration
exclude_modes = tpc_noise, tpc_rn_8pmts, tpc_commissioning_pmtgain, tpc_rn_6pmts, tpc_rn_12_pmts, nVeto_LED_calibration,tpc_rn_12pmts, nVeto_LED_calibration_2
us_only = False
hs06_test_run = False
raw_records_rse = UC_OSG_USERDISK
records_rse = UC_MIDWAY_USERDISK
peaklets_rse = UC_OSG_USERDISK
events_rse = UC_MIDWAY_USERDISK
min_run_number = 1
max_run_number = 999999
max_daily = 2000
chunks_per_job = 10
lower_memory = 14500
lower_disk = 50000
combine_memory = 60000
combine_disk = 120000
upper_memory = 60000
upper_disk = 120000
dagman_retry = 2
dagman_maxidle = 5000
dagman_maxjobs = 5000
```

**Comment by shenyangshi** [comment]
Did you add any `include_data_types`  dtype in your local xenon_config

**Comment by dachengx** [comment]
> Just want to comment here: raw_records_mv are very small, and it doesn't worth the effort and resources to make them per-chunk job in my opinion.

Ah! Then we need to rethink.

**Comment by dachengx** [comment]
If I do `include_data_types = events_nv, events_mv`, I will also see the error.

To prevent confusion in the future I added this PR https://github.com/XENONnT/outsource/pull/222.

**Comment by dachengx** [comment]
> Just want to comment here: raw_records_mv are very small, and it doesn't worth the effort and resources to make them per-chunk job in my opinion.

You suggestion is done in https://github.com/XENONnT/outsource/pull/223
