### ISSUE TITLE
Adding `SDSC_NSDF_USERDISK` into `_rse_site_map`

### ISSUE THREAD

**Issue by FaroutYLq** [XENONnT/outsource#53]
Hi @rynge! Do you know what should we do to add the coming rse `SDSC_NSDF_USERDISK` to [here](https://github.com/XENONnT/outsource/blob/c2db0873adb97f24fc04386eb53f5fea74f010d9/outsource/Outsource.py#L46-L59)?

**Comment by rynge** [comment]
For Outsource, I think you only need a line here:

https://github.com/XENONnT/outsource/blob/master/outsource/Outsource.py#L46

Map it to US like the existing ones. The second place you need to update is Strax, where I think the actual download logic lives today.

**Comment by FaroutYLq** [comment]
> Map it to US like the existing ones.
Will this be enough? `'SDSC_NSDF_USERDISK':    {'expr': 'GLIDEIN_Country == "US"'}`

On the other hand, I am not sure I understand this why it has anything to do with strax. I checked [strax_wrapper](https://github.com/XENONnT/outsource/blob/master/outsource/workflow/strax-wrapper.sh) and [runstrax](https://github.com/XENONnT/outsource/blob/master/outsource/workflow/runstrax.py) and I don't think there is something site related at first glance?

**Comment by rynge** [comment]
Yes, that is correct for Outsource. Sorry, the download code is in admix. I don't know that code very well, but here is a starting point:

https://github.com/XENONnT/admix/blob/74b4c58fa2037f92616851f4879ef6c456dc2ec4/admix/download.py#L31

**Comment by FaroutYLq** [comment]
Perfect. Thanks @rynge. I will handle the admix part. I think this issue for outsource can be closed now if downloading is the only concern left.
