### ISSUE TITLE
replace /xenon paths

### ISSUE THREAD

**Issue by jmosbacher** [XENONnT/outsource#61]
We need to replace `/xenon` paths with `/ospool/uc-shared/project/xenon`
probably just the cutax location?

**Comment by FaroutYLq** [comment]
Thanks for starting this issue. Yes we have[ cutax tarball](https://github.com/XENONnT/outsource/blob/fd750a0683abd1b3afd42ea2fa8b368c618d47a5/outsource/Outsource.py#L250) and the [scratch space](https://github.com/XENONnT/outsource/blob/fd750a0683abd1b3afd42ea2fa8b368c618d47a5/outsource/Outsource.py#L645). I think @rynge will start some initial PR on how to deal with the latter one.

**Comment by FaroutYLq** [comment]
#66 ongoing construction

**Comment by FaroutYLq** [comment]
Fixed
