### ISSUE TITLE
Want to overwrite package like what we did for cutax

### ISSUE THREAD

**Issue by FaroutYLq** [XENONnT/outsource#74]
Upload local tarball and override the software version in environment. This should be very beneficial for debugging.

**Comment by FaroutYLq** [comment]
A nice start: https://github.com/XENONnT/outsource/pull/175#pullrequestreview-2307376283

**Comment by FaroutYLq** [comment]
Better: can we put something like this into `xenon_config`:
```
to_overwrite_packages = cutax,strax,straxen
```

**Comment by dachengx** [comment]
> Better: can we put something like this into `xenon_config`:
> 
> ```
> to_overwrite_packages = cutax,strax,straxen
> ```

I think we want to be consistent when running and submitting jobs. So if we set `to_overwrite_packages = cutax,strax,straxen` but strax is not editable user-installed, we should raise error.

**Comment by FaroutYLq** [comment]
Sure I agree with you on this. Later we might consider other packages beyond strax/straxen, for example utilix. That was the motivation [here](https://github.com/XENONnT/outsource/issues/74#issuecomment-2353611864)

**Comment by dachengx** [comment]
We should also warn of any key package that will influence job submission behavior if it is locally installed. Maybe utilix, admix, rucio, and pymongo should be warned.
