### ISSUE TITLE
Specifying raw_records_rse is not working

### ISSUE THREAD

**Issue by FaroutYLq** [XENONnT/outsource#93]
Details [here](https://xenonnt.slack.com/archives/C048FE2U3KN/p1696832109261139). We are still downloading from Europe even though we specified SDSC_NSDF_USERDISK as raw_records_rse.

**Comment by FaroutYLq** [comment]
This turns out to be more about a admix issue, we need to find a way to pass rse requirement into strax context

**Comment by dachengx** [comment]
Maybe the `straxen.storage.RucioRemoteFrontend` is not clever enough to download data only from a specified RSE. We might want to improve this by a PR in straxen.

**Comment by cfuselli** [comment]
Hi, I think I remember that the raw_records_rse filtered on runs that have raw records there, but it is not a hard constraint to download from there, as rucio will make that choice for you and download from the best rse at that moment given distance, network traffic etc.. not sure though..
